{"errorMessage": "duplicate key value violates unique constraint \"unique_departure\"\nDETAIL:  Key (flight_number, departure_scheduled_time, departure_actual_time)=(1173, 2023-12-01 05:00:00, 2023-12-01 05:31:00) already exists.\nCONTEXT:  COPY departures, line 1\n", "errorType": "UniqueViolation", "requestId": "0d34ce87-6657-4a8f-8868-1eee2a0cb801", "stackTrace": ["  File \"/var/task/aviations3_to_rds.py\", line 242, in main\n    insert_bulk_data_from_dataframe(conn, df)\n", "  File \"/var/task/aviations3_to_rds.py\", line 149, in insert_bulk_data_from_dataframe\n    cur.copy_expert(\n"]}