{"errorMessage": "duplicate key value violates unique constraint \"unique_departure\"\nDETAIL:  Key (flight_number, departure_scheduled_time, departure_actual_time)=(5641, 2023-12-01 06:00:00, 2023-12-01 06:21:00) already exists.\nCONTEXT:  COPY departures, line 1\n", "errorType": "UniqueViolation", "requestId": "272b6dce-9e07-486a-bf3a-992d40ca7a6d", "stackTrace": ["  File \"/var/task/departure_batch.py\", line 243, in main\n    insert_bulk_data_from_dataframe(conn, df)\n", "  File \"/var/task/departure_batch.py\", line 149, in insert_bulk_data_from_dataframe\n    cur.copy_expert(\n"]}