{"errorMessage": "duplicate key value violates unique constraint \"unique_departure\"\nDETAIL:  Key (flight_number, departure_scheduled_time, departure_actual_time)=(1301, 2023-12-01 05:55:00, 2023-12-01 06:05:00) already exists.\nCONTEXT:  COPY departures, line 1\n", "errorType": "UniqueViolation", "requestId": "ae28291b-d0f0-446b-af27-714afe57fffd", "stackTrace": ["  File \"/var/task/aviations3_to_rds.py\", line 243, in main\n    insert_bulk_data_from_dataframe(conn, df)\n", "  File \"/var/task/aviations3_to_rds.py\", line 149, in insert_bulk_data_from_dataframe\n    cur.copy_expert(\n"]}