{"errorMessage": "duplicate key value violates unique constraint \"unique_flight\"\nDETAIL:  Key (flight_number, arrival_scheduled_time, arrival_actual_time)=(1696, 2023-12-01 05:55:00, 2023-12-01 06:00:00) already exists.\nCONTEXT:  COPY arrivals, line 1\n", "errorType": "UniqueViolation", "requestId": "f45f34a3-47a7-439b-8a02-07849eb76f2d", "stackTrace": ["  File \"/var/task/aviations3_to_rds.py\", line 287, in main\n    insert_bulk_data_from_dataframe(conn, df)\n", "  File \"/var/task/aviations3_to_rds.py\", line 151, in insert_bulk_data_from_dataframe\n    cur.copy_expert(\n"]}