{"errorMessage": "An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-east-1:871770651017:function:departures_Zurich", "errorType": "ResourceNotFoundException", "requestId": "c233dfca-b4e6-432d-89a6-436d3731f19f", "stackTrace": ["  File \"/var/task/parent_departures_lambda.py\", line 38, in lambda_handler\n    lambda_client.invoke(\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 569, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 1023, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}