{"errorMessage": "duplicate key value violates unique constraint \"unique_flight\"\nDETAIL:  Key (flight_number, arrival_scheduled_time, arrival_actual_time)=(810, 2023-12-01 05:50:00, 2023-12-01 06:19:00) already exists.\nCONTEXT:  COPY arrivals, line 1\n", "errorType": "UniqueViolation", "requestId": "c59406a4-9efa-41fe-8753-3be6b55dc98c", "stackTrace": ["  File \"/var/task/arrival_batch.py\", line 246, in main\n    insert_bulk_data_from_dataframe(conn, df)\n", "  File \"/var/task/arrival_batch.py\", line 150, in insert_bulk_data_from_dataframe\n    cur.copy_expert(\n"]}