{"errorMessage": "duplicate key value violates unique constraint \"unique_flight\"\nDETAIL:  Key (flight_number, arrival_scheduled_time, arrival_actual_time)=(1696, 2023-12-01 05:55:00, 2023-12-01 06:00:00) already exists.\nCONTEXT:  COPY arrivals, line 1\n", "errorType": "UniqueViolation", "requestId": "8ec822ed-f9c4-4576-b3f7-efaffd00e18f", "stackTrace": ["  File \"/var/task/aviations3_to_rds.py\", line 248, in main\n    insert_bulk_data_from_dataframe(conn, df)\n", "  File \"/var/task/aviations3_to_rds.py\", line 150, in insert_bulk_data_from_dataframe\n    cur.copy_expert(\n"]}